apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ha-proxy-metrics-monitor
spec:
  selector:
    matchLabels:
      app: ha-proxy 
  namespaceSelector:
    matchNames:
      - ha-proxy
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
