apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ha-proxy
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 5s
