apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: munyard-dev-tls
  namespace: ha-proxy
spec:
  secretName: munyard-dev-tls
  dnsNames:
  - "munyard.dev"
  - "bfstats.io"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
