apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 73.2.0
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        prometheus:
          prometheusSpec:
            serviceMonitorSelector: {}
            retention: "60d"
            retentionSize: "5GiB"

            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "local-path"
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 10Gi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  