apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`stats.home.net`)
    kind: Rule
    services:
    - name: kube-prometheus-stack-grafana
      port: 80
  - match: Host(`prometheus.home.net`)
    kind: Rule
    services:
    - name: kube-prometheus-stack-prometheus
      port: 9090
