prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    retention: "60d"
    retentionSize: "5GiB"

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "local-path"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi