apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-azure-disk
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uses default Azure Disk storage class
