apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      nodeSelector:
        kubernetes.io/hostname: bethany
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.12-alpine
          env:
            - name: CLICKHOUSE_USER
              value: "chuser"
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
            - name: CLICKHOUSE_PASSWORD
              value: "chpassword"
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          volumeMounts:
            - name: stats-data
              mountPath: /var/lib/clickhouse
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_NICE
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8123
              httpHeaders:
                - name: Authorization
                  value: "Basic Y2h1c2VyOmNocGFzc3dvcmQ="  # base64 of chuser:chpassword
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
              httpHeaders:
                - name: Authorization
                  value: "Basic Y2h1c2VyOmNocGFzc3dvcmQ="  # base64 of chuser:chpassword
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: stats-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: clickhouse
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: native
      port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: clickhouse-http
  namespace: clickhouse
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`clickhouse.home.net`)
    kind: Rule
    services:
    - name: clickhouse-service
      port: 8123
