apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  users.xml: |
    <clickhouse>
      <users>
        <default>
          <password></password>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
          <access_management>1</access_management>
        </default>
      </users>
      <profiles>
        <default>
          <http_max_uri_size>209715200</http_max_uri_size>
          <max_query_size>209715200</max_query_size>
        </default>
      </profiles>
    </clickhouse>
  config.xml: |
    <clickhouse>
      <text_log>
        <level>information</level>
        <ttl><![CDATA[DELETE WHERE event_date < today() - INTERVAL 7 DAY]]></ttl>
      </text_log>
    </clickhouse>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: clickhouse
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      nodeSelector:
        kubernetes.io/hostname: bethany
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.12-alpine
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          volumeMounts:
            - name: stats-data
              mountPath: /var/lib/clickhouse
            - name: config
              mountPath: /etc/clickhouse-server/users.d/users.xml
              subPath: users.xml
            - name: config
              mountPath: /etc/clickhouse-server/config.d/config.xml
              subPath: config.xml
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_NICE
          resources:
            limits:
              memory: "32Gi"
            requests:
              memory: "4Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: stats-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc
        - name: config
          configMap:
            name: clickhouse-config

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: clickhouse
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: native
      port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: clickhouse-http
  namespace: clickhouse
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`clickhouse.home.net`)
    kind: Rule
    services:
    - name: clickhouse-service
      port: 8123
