apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  home-net.server: |
    home.net:53 {
        errors
        cache 30
        template IN A {
            match (.*)\.home\.net\.
            answer "{{ .Name }} 60 IN A 192.168.1.220"
            answer "{{ .Name }} 60 IN A 192.168.1.221"
            answer "{{ .Name }} 60 IN A 192.168.1.222"
        }
    }
