apiVersion: v1
kind: Service
metadata:
  name: coredns-nodeport
  namespace: kube-system
spec:
  type: NodePort
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns
      port: 53
      targetPort: 53
      nodePort: 30553
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      nodePort: 30553
      protocol: TCP
