version: "3.8"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /home/dietpi/config-jackett:/config
      - /media-data/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - tweety
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /home/dietpi/config-sonarr:/config
      - /media-data/tv:/tv
      - /media-data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - tweety
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /home/dietpi/config-radarr:/config
      - /media-data/movies:/movies
      - /media-data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - tweety
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /home/dietpi/config-sabnzbd:/config
      - /media-data/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - tweety
  #  qb:
  #    image: lscr.io/linuxserver/qbittorrent:latest
  #    container_name: qb
  #    environment:
  #      - PUID=0
  #      - PGID=0
  #      - TZ=Australia/Brisbane
  #      - WEBUI_PORT=8090
  #      - TORRENTING_PORT=6881
  #    volumes:
  #      - /home/dietpi/config-qb:/config
  #      - /media-data/downloads:/downloads
  #    ports:
  #      - 8090:8090
  #      - 6881:6881
  #      - 6881:6881/udp
  #    restart: unless-stopped
  #    networks:
  #      - tweety
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /home/dietpi/config-transmission:/config
      - /media-data/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - tweety
networks:
  tweety: null
