version: "3.8"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /media-data/config-jackett:/config
      - /media-data/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - tweety
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /media-data/config-sonarr:/config
      - /media-data/tv:/tv
      - /media-data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - tweety
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /media-data/config-radarr:/config
      - /media-data/movies:/movies
      - /media-data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - tweety
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
    volumes:
      - /media-data/config-sabnzbd:/config
      - /media-data/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - tweety
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Brisbane
      - USER=admin
      - PASS=5uea5NQNH2OqT9VEg4JJjBHvt
    volumes:
      - /media-data/config-transmission:/config
      - /media-data/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - tweety
  unpackerr:
    image: golift/unpackerr
    volumes:
      - /media-data/downloads/complete:/downloads
    user: 0:0
    environment:
      - TZ=Australia/Brisbane
      - UN_QUIET=false
      - UN_DEBUG=false
      - UN_ERROR_STDERR=false
      - UN_LOG_QUEUES=1m
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      - UN_ACTIVITY=false
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=7bcc5fbbafc34402a2c05fe6b43bb483
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=f483632aff8d412cbcd542fa374d8d85
    restart: unless-stopped
    networks:
      - tweety
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/Brisbane
    ports:
      - 5055:5055
    volumes:
      - /media-data/lxc/overseerr:/app/config
    restart: unless-stopped

networks:
  tweety: null
