version: "3.3"
services:
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    networks:
      - otel
  prometheus:
    image: prom/prometheus:latest
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    networks:
      - otel
    configs:
      - source: prometheus-config
        target: /etc/prometheus.yaml
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    volumes:
      - loki_data:/loki
    networks:
      - otel
  tempo:
    image: grafana/tempo:latest
    command:
      - -config.file=/etc/tempo-config.yaml
    ports:
      - 4317:43317 # gRPC (OTLP receiver)
      - 3200:3200 # Tempo internal port
      - 3110:3110 # HTTP API for Grafana queries
    volumes:
      - tempo_data:/var/tempo
    configs:
      - source: tempo-config
        target: /etc/tempo-config.yaml
    networks:
      - otel
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana # This persists Grafana's database and config
    depends_on:
      - prometheus
      - loki
      - tempo
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    networks:
      - otel
  influxdb:
    image: influxdb:2
    ports:
      - 8086:8086
    volumes:
      - /media-data/lxc/otel/influxdb/data:/var/lib/influxdb2
      - /media-data/lxc/otel/influxdb/config:/etc/influxdb2
    networks:
      - otel
volumes:
  seq_data: null
  grafana_data: null # New volume for Grafana persistence
  prometheus_data: null # Added for Prometheus data persistence
  loki_data: null # Added for Loki data persistence
  tempo_data: null # Added for Tempo data persistence
configs:
  tempo-config:
    file: ./tempo/tempo.yaml
  prometheus-config:
    file: ./prometheus/prometheus.yaml
networks:
  otel: null
