apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-registry-pvc
  namespace: container-registry
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi