apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-net-tls
  namespace: container-registry
spec:
  secretName: home-net-tls
  privateKey:
    algorithm: RSA
    size: 4096
  dnsNames:
  - "hub.home.net"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
